## Load audio

In [1]:
import IPython.display as ipd
audio = "../audio/7143-88743-0029.flac"
print('Original audio:')
ipd.display(ipd.Audio(audio))

Original audio:


## SpiritLM tokenizers

In [2]:
from spiritlm.speech_tokenizer import spiritlm_base, spiritlm_expressive

### SpiritLM-BASE tokenizer

In [3]:
## Load the tokenizer
tokenizer_base = spiritlm_base()

/home/.conda/envs/spiritlm/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [4]:
## encode_units
print('SpiritLM-BASE: Encode audio into units (not deduplicated) \n', '-'*20)
units = tokenizer_base.encode_units(audio)
print(units)

## encode_string
print('\nSpiritLM-BASE: Encode audio into string (deduplicated and sorted units) \n', '-'*20)
string_tokens = tokenizer_base.encode_string(audio)
print(string_tokens)

## decode from units
print('\nSpiritLM-BASE: Decode back to audio from units (not deduplicated) \n', '-'*20)
resyn_wav = tokenizer_base.decode(units, speaker_id=2)
ipd.display(ipd.Audio(resyn_wav, rate=16000))

## decode from string
print('\nSpiritLM-BASE: Decode back to audio from string (deduplicated and sorted units) \n', '-'*20)
resyn_dedup_wav = tokenizer_base.decode(string_tokens, speaker_id=2)
ipd.display(ipd.Audio(resyn_dedup_wav, rate=16000))

SpiritLM-BASE: Encode audio into units (not deduplicated) 
 --------------------
{'audio': 'examples/audio/7143-88743-0029.flac', 'hubert': '99 49 38 149 149 71 423 427 492 288 315 153 153 389 497 412 247 354 7 96 452 452 176 266 266 77 248 336 336 211 166 65 94 224 224 148 492 191 440 440 41 41 457 79 382 451 332 216 114 340 478 74 79 370 272 370 370 53 477 65 171 60 258 111 111 111 111 338 338 23 23 338 23 338 338 338 7 338 338 149 406 7 361 361 361 99 99 99 99 99 99 99 209 209 209 209 209 479 50 50 7 149 149 35 35 130 130 169 169 72 434 119 272 4 249 245 245 433 159 294 139 359 343 269 302 226 370 216 459 424 424 226 382 7 58 138 428 397 350 350 306 306 306 84 11 171 171 60 314 227 227 355 9 58 138 226 370 272 382 334 330 176 176 307 145 248 493 64 44 388 7 111 111 111 111 23 23 481 149 149 80 70 431 457 79 79 249 249 245 245 245 433 433 316 316 180 458 458 458 86 86 225 103 60 96 119 119 129 356 218 4 259 259 392 490 75 488 166 65 171 60 7 54 54 85 85 361 361'}

SpiritLM-BASE: Enco


SpiritLM-BASE: Decode back to audio from string (deduplicated and sorted units) 
 --------------------


### SpiritLM-EXPRESSIVE Tokenizer

In [5]:
## Load the tokenizer
tokenizer_expressive = spiritlm_expressive()

  [INFO]: device is not None, use cuda:0
  [INFO]    > call by:torchfcpe.tools.spawn_infer_cf_naive_mel_pe_from_pt
  [WARN] args.model.use_harmonic_emb is None; use default False
  [WARN]    > call by:torchfcpe.tools.spawn_cf_naive_mel_pe


/home/.conda/envs/spiritlm/lib/python3.10/site-packages/torchfcpe/models_infer.py:191: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(pt_path, map_location=

In [6]:
## encode_units
print('SpiritLM-EXPRESSIVE: Encode audio into units (not deduplicated) \n', '-'*20)
units = tokenizer_expressive.encode_units(audio)
print(units)

## encode_string
print('\nSpiritLM-EXPRESSIVE: Encode audio into string (deduplicated and sorted units) \n', '-'*20)
string_tokens = tokenizer_expressive.encode_string(audio)
print(string_tokens)

## decode from units
print('\nSpiritLM-EXPRESSIVE: Decode back to audio from units (not deduplicated) \n', '-'*20)
resyn_wav = tokenizer_expressive.decode(units, speaker_id=2)
ipd.display(ipd.Audio(resyn_wav, rate=16000))

## decode from string
print('\nSpiritLM-EXPRESSIVE: Decode back to audio from string (deduplicated and sorted units) \n', '-'*20)
resyn_dedup_wav = tokenizer_expressive.decode(string_tokens, speaker_id=2)
ipd.display(ipd.Audio(resyn_dedup_wav, rate=16000))

SpiritLM-EXPRESSIVE: Encode audio into units (not deduplicated) 
 --------------------
{'audio': 'examples/audio/7143-88743-0029.flac', 'hubert': '99 49 38 149 149 71 423 427 492 288 315 153 153 389 497 412 247 354 7 96 452 452 176 266 266 77 248 336 336 211 166 65 94 224 224 148 492 191 440 440 41 41 457 79 382 451 332 216 114 340 478 74 79 370 272 370 370 53 477 65 171 60 258 111 111 111 111 338 338 23 23 338 23 338 338 338 7 338 338 149 406 7 361 361 361 99 99 99 99 99 99 99 209 209 209 209 209 479 50 50 7 149 149 35 35 130 130 169 169 72 434 119 272 4 249 245 245 433 159 294 139 359 343 269 302 226 370 216 459 424 424 226 382 7 58 138 428 397 350 350 306 306 306 84 11 171 171 60 314 227 227 355 9 58 138 226 370 272 382 334 330 176 176 307 145 248 493 64 44 388 7 111 111 111 111 23 23 481 149 149 80 70 431 457 79 79 249 249 245 245 245 433 433 316 316 180 458 458 458 86 86 225 103 60 96 119 119 129 356 218 4 259 259 392 490 75 488 166 65 171 60 7 54 54 85 85 361 361', 'pitch': '39 3


SpiritLM-EXPRESSIVE: Decode back to audio from string (deduplicated and sorted units) 
 --------------------


## Test load each component

In [7]:
from spiritlm.speech_tokenizer.hubert import spiritlm_hubert
from spiritlm.speech_tokenizer.hifigan import spiritlm_base_hifigan, spiritlm_expressive_hifigan_w2v2
from spiritlm.speech_tokenizer.f0 import spiritlm_expressive_f0
from spiritlm.speech_tokenizer.style_encoder import spiritlm_expressive_style_encoder_w2v2

### Hubert Tokenizer

In [8]:
hubert_tokenizer = spiritlm_hubert()
print("hubert_tokenizer(audio):\n", hubert_tokenizer(audio))

hubert_tokenizer(audio):
 tensor([ 99,  49,  38, 149, 149,  71, 423, 427, 492, 288, 315, 153, 153, 389,
        497, 412, 247, 354,   7,  96, 452, 452, 176, 266, 266,  77, 248, 336,
        336, 211, 166,  65,  94, 224, 224, 148, 492, 191, 440, 440,  41,  41,
        457,  79, 382, 451, 332, 216, 114, 340, 478,  74,  79, 370, 272, 370,
        370,  53, 477,  65, 171,  60, 258, 111, 111, 111, 111, 338, 338,  23,
         23, 338,  23, 338, 338, 338,   7, 338, 338, 149, 406,   7, 361, 361,
        361,  99,  99,  99,  99,  99,  99,  99, 209, 209, 209, 209, 209, 479,
         50,  50,   7, 149, 149,  35,  35, 130, 130, 169, 169,  72, 434, 119,
        272,   4, 249, 245, 245, 433, 159, 294, 139, 359, 343, 269, 302, 226,
        370, 216, 459, 424, 424, 226, 382,   7,  58, 138, 428, 397, 350, 350,
        306, 306, 306,  84,  11, 171, 171,  60, 314, 227, 227, 355,   9,  58,
        138, 226, 370, 272, 382, 334, 330, 176, 176, 307, 145, 248, 493,  64,
         44, 388,   7, 111, 111, 111, 

### Pitch Tokenizer

In [9]:
f0_tokenizer = spiritlm_expressive_f0()
print("f0_tokenizer(audio):\n", f0_tokenizer(audio))

  [INFO]: device is not None, use cuda:0
  [INFO]    > call by:torchfcpe.tools.spawn_infer_cf_naive_mel_pe_from_pt
  [WARN] args.model.use_harmonic_emb is None; use default False
  [WARN]    > call by:torchfcpe.tools.spawn_cf_naive_mel_pe
f0_tokenizer(audio):
 tensor([39, 39, 39, 48, 56, 40, 42, 39, 51, 40, 43, 54,  3, 35, 39, 25, 58, 26,
        44, 40, 13, 20, 46, 41, 26, 40, 26, 56, 41, 46, 46, 41, 41, 40, 40, 40,
        39, 39, 57, 59, 59, 59, 59, 59, 59, 59, 59, 20, 20, 20, 35, 35, 13,  3,
         9,  6,  0, 20, 57, 56, 56, 56, 56, 59, 44, 57, 41, 59, 42, 51, 59, 57,
        59, 59, 39, 39, 46, 56, 58, 41, 41, 40, 39, 39, 39, 59, 59, 59, 15, 27,
        13, 55, 13, 27, 35, 36,  3, 53,  3, 26, 43, 53, 54, 39, 25, 14, 41, 46,
        46, 46, 46, 41, 41, 41], device='cuda:0')


### Style Tokenizer

In [10]:
style_tokenizer = spiritlm_expressive_style_encoder_w2v2()
print("style_tokenizer(audio):\n", style_tokenizer(audio))

Some weights of Wav2Vec2StyleEncoder were not initialized from the model checkpoint at checkpoints/speech_tokenizer/style_encoder_w2v2 and are newly initialized: ['_float_tensor']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


style_tokenizer(audio):
 tensor([71, 71, 71, 71, 71, 71, 71, 71, 71, 83], device='cuda:0')


### Hifi-GAN Vocoders

In [11]:
# Base vocoder
base_vocoder = spiritlm_base_hifigan()
wav = base_vocoder(hubert_tokenizer(audio), speaker_id=1).cpu().numpy()
ipd.Audio(wav, rate=16000)

In [12]:
# Expressive vocoder
expressive_vocoder = spiritlm_expressive_hifigan_w2v2()
wav_ex = expressive_vocoder(
            code=hubert_tokenizer(audio),
            f0_code=f0_tokenizer(audio),
            style_code=style_tokenizer(audio),
            dur_pred=False,
            speaker_id=1,
            not_dedup_code=True,
        ).cpu().numpy()
ipd.Audio(wav_ex, rate=16000)